package cli

import (
	"fmt"
	"log"
	"strconv"

	"github.com/AlecAivazis/survey/v2"
	"github.com/christian-gama/autocommit/chat"
)

type configAnswers struct {
	Model        string
	OpenAIAPIKey string
	Temperature  float32
}

func printWelcome() {
	fmt.Println("Welcome to AutoCommit! Let's get started by setting up your configuration.")
	fmt.Println("You can reset these settings later by running 'autocommit reset'.")
	fmt.Println("")
}

func askUserForConfig() *configAnswers {
	printWelcome()

	openaiApiKeyPrompt := survey.Password{
		Message: "OpenAI API Key",
		Help:    "The API key to use for OpenAI. Get one at https://platform.openai.com/account/api-keys",
	}

	modelPrompt := createModelPrompt()

	temperaturePrompt := survey.Input{
		Message: "Temperature",
		Help:    "Temperature refers to a parameter that controls the randomness of the output generated by the model.",
		Default: "0.3",
	}

	var answers configAnswers

	err := survey.Ask([]*survey.Question{
		{
			Name:   "OpenAIAPIKey",
			Prompt: &openaiApiKeyPrompt,
			Validate: func(ans any) error {
				return chat.ValidateAPIKey(ans.(string))
			},
		},
		{
			Name:     "Model",
			Prompt:   &modelPrompt,
			Validate: survey.Required,
		},
		{
			Name:      "Temperature",
			Prompt:    &temperaturePrompt,
			Transform: convertToFloat32,
			Validate: func(ans any) error {
				f, err := strconv.ParseFloat(ans.(string), 32)
				if err != nil {
					return err
				}

				return chat.ValidateTemperature(float32(f))
			},
		},
	}, &answers)
	if err != nil {
		log.Fatalf("Failed to get config input: %v", err)
	}

	return &answers
}

func createModelPrompt() survey.Select {
	models := []string{}
	for model := range chat.ModelMap {
		models = append(models, model)
	}

	return survey.Select{
		Message: "Model name",
		Help:    "A model can be an algorithm or a set of algorithms that have been trained on data to make predictions or decisions.",
		Default: chat.GPT3Dot5Turbo16k,
		Options: models,
		Description: func(value string, index int) string {
			if value == chat.GPT4 || value == chat.GPT432K {
				return "Beta - May not be available for all users"
			}

			return ""
		},
		VimMode: true,
	}
}
